# SITE CONFIGURATION
baseurl: "/open-journalism-project" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: The Open Journalism Project
  avatar: img/oj-avatar.jpg
  description: "Fun with journalism and code." # used by search engines
  
  # Header and footer text
  header_text: >
     
     <p>A GUIDE TO ONLINE JOURNALISM</p>
  footer_text: >
   Code and journalism for fun.
  
  # Icons
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "pippinlee/open-journalism-project"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "openjo"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: "UA-58629705-1"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Check out resources"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 6
paginate_path: "blog/page:num"
  
# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed